//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDNbaikiemtragiuaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdnKhoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bdnKhoa()
        {
            this.bdnSinhViens = new HashSet<bdnSinhVien>();
        }
    
        public string BdnMaKH { get; set; }
        public string BdnTenKH { get; set; }
        public Nullable<bool> BdnTrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bdnSinhVien> bdnSinhViens { get; set; }
    }
}
