//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDNbaikiemtragiuaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bdnSinhVien
    {
        public string BdnMaSV { get; set; }
        public string BdnHoSV { get; set; }
        public string BdnTenSV { get; set; }
        public Nullable<System.DateTime> BdnNgaySinh { get; set; }
        public Nullable<bool> BdnPhai { get; set; }
        public string BdnPhone { get; set; }
        public string BdnEmail { get; set; }
        public string BdnMaKH { get; set; }
    
        public virtual bdnKhoa bdnKhoa { get; set; }
    }
}
